Update CONTRIBUTING.md and README.md
Remi-Gau/brainhack_jupyter_book pull request #2
Opened 2021-03-06 23:24 UTC by complexbrains

This PR separates the updates in PR #1 into the newly organized README.md and CONTRIBUTING.md files as necessary. 

So please ignore the previous PR and review the changes in this one @Remi-Gau @anibalsolon @PeerHerholz @SamGuay @htwangtw.

Thank you 🤗

2021-03-07 07:41 UTC, Remi-Gau requested changes
Couple of suggestions. :-)

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
> +
You can do that with the following command where `upstream` is the nickname you give to the Brainhack Jupyter Book repository.

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
> +`git checkout master`
```suggestion
`git checkout main`
```

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
> +`git merge upstream/master`
```suggestion
`git merge upstream/main`
```

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
> +`$ git pull upstream master`
```suggestion
`$ git checkout main`
`$ git pull upstream main`
```

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
> +pip install jupyter-book
I would not have this here since technically people have already installed this by doing a `pip install -r requirements.txt`

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
> +    -  [Cywin](https://www.cygwin.com/)
Do you think you could "merge" some of that with the section `Viewing the Brainhack Book` that talks about installing python and git.

We pointed to the datalad handbook for the python install as it covers all OS.

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
>  1. If you are using `virtualenv`:
```suggestion
1. If you are using `venv`:
```

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
> +or you can use the following
```suggestion
or you can use the following with `virtualenv`
```

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
I think we should follow up both sections for `venv` and `virtualenv` with the same call to `pip install -r requirements.txt` to make sure people have installed evrything.

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
>  jupyter-book build brainhack_book
Maybe here we could make a mention of Haoting's Make file:

Typing the following in the book will be enough to build the book.

```
make book
```

2021-03-07 07:41 UTC, Remi-Gau commented on CONTRIBUTING.md
>  jupyter-book build brainhack_book
We can even add a pointer to the make section of the Turing way in case people want to know more.

2021-03-07 16:13 UTC, SamGuay commented on CONTRIBUTING.md
>  git clone git@github.com:brainhackorg/brainhack_jupyter_book.git
```suggestion
git clone git@github.com:YOURUSERNAME/brainhack_jupyter_book.git
```

2021-03-07 16:13 UTC, SamGuay commented on CONTRIBUTING.md
> +
```suggestion

The first time you try to sync your fork, you may have to set the upstream branch:
```bash
git remote add upstream https://github.com/brainhack_jupyter_book/brainhack_jupyter_book.git
git remote -v # Making sure the upstream repo is listed.
```
```
```
for some reason, the 3 ending \`\`\` don't appear in review mode..

2021-03-07 16:13 UTC, SamGuay commented on CONTRIBUTING.md
> +### Synchronize your master branch with the upstream master branch: :arrows_counterclockwise:
```suggestion
### Synchronize your main branch with the upstream main branch: :arrows_counterclockwise:
```

2021-03-07 16:13 UTC, SamGuay commented on CONTRIBUTING.md
> +`$ git pull upstream master`
I would remove the `$` since code before doesn't show the prompt.

2021-03-07 16:13 UTC, SamGuay commented on CONTRIBUTING.md
> +    -  [Cywin](https://www.cygwin.com/)
+1

2021-03-07 16:13 UTC, SamGuay commented on CONTRIBUTING.md
> +
```suggestion
You can then create a new branch to work on an issue. Using a new branch allows you to follow the standard GitHub workflow when making changes. This [guide](https://guides.github.com/introduction/flow/) provides a useful overview of this workflow. Please keep the name of your branch short and self-explanatory.
`git checkout -b MYBRANCH`
```

2021-03-07 16:13 UTC, SamGuay commented on CONTRIBUTING.md
> +For example, to update your master branch on your local cloned repository:
```suggestion
For example, to update your main branch on your local cloned repository:
```

2021-03-07 19:16 UTC, complexbrains commented on CONTRIBUTING.md
> +
I believe this resolved with the addition done by @SamGuay?

2021-03-07 19:57 UTC, complexbrains commented on CONTRIBUTING.md
>  jupyter-book build brainhack_book
@Remi-Gau emi  Did you mean [these instructions](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/README.md) by Turing Way?

2021-03-07 21:53 UTC, Remi-Gau commented on CONTRIBUTING.md
>  jupyter-book build brainhack_book
nope

that one

https://the-turing-way.netlify.app/reproducible-research/make.html

2021-03-08 08:07 UTC, Remi-Gau requested changes

2021-03-08 08:07 UTC, Remi-Gau commented on CONTRIBUTING.md
> +```bash
I was viewing this file here:https://github.com/complexbrains/brainhack_jupyter_book/blob/isil-update_readme/CONTRIBUTING.md

And  there seems to be a big "verbatim" section in the middle that mixes code and non code.

That should probably be fixed.

2021-03-08 12:58 UTC, SamGuay commented on CONTRIBUTING.md
> +```bash
Yes, I had commented about GitHub not properly rendering the code block with \`\`\` for some reason inside the suggestion block...

2021-03-08 14:21 UTC, htwangtw commented on CONTRIBUTING.md
> +```bash
I believe you need an empty line after the code block?

2021-03-08 14:28 UTC, SamGuay commented on CONTRIBUTING.md
> +```bash
I tried many things and nothing worked so far.. #bummer

2021-03-08 14:33 UTC, htwangtw commented on CONTRIBUTING.md
> +```bash
:disappointed:

2021-03-08 15:05 UTC, complexbrains commented on CONTRIBUTING.md
> +```bash
I believe it should be resolved with the last PR now.

2021-03-09 05:27 UTC, Remi-Gau approved these changes
Woooohoooo!!! :rocket: 

Good to go

2021-03-09 05:27 UTC, merged